image: docker:latest
services:
  - docker:dind

variables:
  TAG: 'latest'

stages:
  - build-publish

develop_docker:
  stage: build-publish
  script:
    - mkdir docker
    - export DOCKER_HOST=$DOCKER_PORT
    - cp -R ./* docker/ || true
    - docker build -t $TAG ./docker/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $TAG
  only:
    - master
  artifacts:
    expire_in: 1 day
    paths:
      - docker/
  variables:
    ASSEMBLY_NAME: AliasMailApi
    TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_PIPELINE_ID
